// {
//     status: 200,
//         statusText: 'OK',
//     headers: Object [AxiosHeaders] {
//     'set-cookie': [
//         'access_jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoicmFkYXIiLCJpc3MiOiJsb2NhbGhvc3QiLCJpYXQiOjE3MTY4OTcxNTYsImV4cCI6MTcxNjg5NzQ1Nn0.dSLATm8rg1xt7Km-_hPQg1alXOkcEqtk2neVK-xGq2g; expires=Tue, 28 May 2024 12:22:36 GM
//         T; Max-Age=1800; path=/; domain=localhost; SameSite=none',
//     'refresh_jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoicmFkYXIiLCJpc3MiOiJsb2NhbGhvc3QiLCJpYXQiOjE3MTY4OTcxNTYsImV4cCI6MTcxNjg5ODk1Nn0.s3JSe63Glh8jLlGlSi1uBeZTX97nnhue3j4NOyY3Y4Y; expires=Tue, 28 May 2024 12:22:36 G
//     MT; Max-Age=1800; path=/; domain=localhost; SameSite=none',
//     'username=radar; expires=Tue, 28 May 2024 12:22:36 GMT; Max-Age=1800; path=/; domain=localhost; SameSite=none'
// ],
//     'content-type': 'application/json; charset=utf-8',
//         etag: '"cma8yus7mh1k"',
//         'content-length': '56',
//         vary: 'Accept-Encoding',
//         date: 'Tue, 28 May 2024 11:52:36 GMT',
//         connection: 'keep-alive',
//         'keep-alive': 'timeout=5'
// },
//     config: {
//         transitional: {
//             silentJSONParsing: true,
//                 forcedJSONParsing: true,
//                 clarifyTimeoutError: false
//         },
//         adapter: [ 'xhr', 'http', 'fetch' ],
//             transformRequest: [ [Function: transformRequest] ],
//         transformResponse: [ [Function: transformResponse] ],
//         timeout: 0,
//             xsrfCookieName: 'XSRF-TOKEN',
//             xsrfHeaderName: 'X-XSRF-TOKEN',
//             maxContentLength: -1,
//             maxBodyLength: -1,
//             env: { FormData: [Function], Blob: [class Blob] },
//         validateStatus: [Function: validateStatus],
//         headers: Object [AxiosHeaders] {
//             Accept: 'application/json, text/plain, */*',
//                 'Content-Type': 'application/json',
//                 Cookie: 'access_jwt=jhg; refresh_jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoicmFkYXIiLCJpc3MiOiJsb2NhbGhvc3QiLCJpYXQiOjE3MTY4OTYwMTcsImV4cCI6MTcxNjg5NzgxN30.TiU3niiShfw-P_sKP9FZq6WN2NBYhIi7shG-H3Cdyfc; username=ra
//             dar',
//             'User-Agent': 'axios/1.7.2',
//                 'Content-Length': '78',
//                 'Accept-Encoding': 'gzip, compress, deflate, br'
//         },
//         method: 'post',
//             url: 'http://localhost:3000/api/handler',
//             data: '{"data":null,"url":"http://localhost/test-api/api/index.php/refreshTokenPair"}',
//             withCredentials: true
//     },
//     request: <ref *1> ClientRequest {
//     _events: [Object: null prototype] {
//         abort: [Function (anonymous)],
//             aborted: [Function (anonymous)],
//             connect: [Function (anonymous)],
//             error: [Function (anonymous)],
//             socket: [Function (anonymous)],
//             timeout: [Function (anonymous)],
//             finish: [Function: requestOnFinish]
//     },
//     _eventsCount: 7,
//         _maxListeners: undefined,
//         outputData: [],
//         outputSize: 0,
//         writable: true,
//         destroyed: true,
//         _last: false,
//         chunkedEncoding: false,
//         shouldKeepAlive: true,
//         maxRequestsOnConnectionReached: false,
//         _defaultKeepAlive: true,
//         useChunkedEncodingByDefault: true,
//         sendDate: false,
//         _removedConnection: false,
//         _removedContLen: false,
//         _removedTE: false,
//         strictContentLength: false,
//         _contentLength: '78',
//         _hasBody: true,
//         _trailer: '',
//         finished: true,
//         _headerSent: true,
//         _closed: true,
//         socket: Socket {
//         connecting: false,
//             _hadError: false,
//             _parent: null,
//             _host: 'localhost',
//             _closeAfterHandlingError: false,
//             _events: [Object],
//             _readableState: [ReadableState],
//             _writableState: [WritableState],
//             allowHalfOpen: false,
//             _maxListeners: undefined,
//             _eventsCount: 6,
//             _sockname: null,
//             _pendingData: null,
//             _pendingEncoding: '',
//             server: null,
//             _server: null,
//             timeout: 5000,
//             parser: null,
//             _httpMessage: null,
//             autoSelectFamilyAttemptedAddresses: [Array],
//             [Symbol(async_id_symbol)]: -1,
//             [Symbol(kHandle)]: [TCP],
//             [Symbol(lastWriteQueueSize)]: 0,
//             [Symbol(timeout)]: Timeout {
//             _idleTimeout: 5000,
//                 _idlePrev: [TimersList],
//                 _idleNext: [Timeout],
//                 _idleStart: 6487338,
//                 _onTimeout: [Function: bound ],
//             _timerArgs: undefined,
//                 _repeat: null,
//                 _destroyed: false,
//                 [Symbol(refed)]: false,
//                 [Symbol(kHasPrimitive)]: false,
//                 [Symbol(asyncId)]: 510674,
//                 [Symbol(triggerId)]: 510672
//         },
//         [Symbol(kBuffer)]: null,
//             [Symbol(kBufferCb)]: null,
//             [Symbol(kBufferGen)]: null,
//             [Symbol(shapeMode)]: true,
//             [Symbol(kCapture)]: false,
//             [Symbol(kSetNoDelay)]: true,
//             [Symbol(kSetKeepAlive)]: true,
//             [Symbol(kSetKeepAliveInitialDelay)]: 1,
//             [Symbol(kBytesRead)]: 0,
//             [Symbol(kBytesWritten)]: 0
//     },
//     _header: 'POST /api/handler HTTP/1.1\r\n' +
//     'Accept: application/json, text/plain, */*\r\n' +
//     'Content-Type: application/json\r\n' +
//     'Cookie: access_jwt=jhg; refresh_jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoicmFkYXIiLCJpc3MiOiJsb2NhbGhvc3QiLCJpYXQiOjE3MTY4OTYwMTcsImV4cCI6MTcxNjg5NzgxN30.TiU3niiShfw-P_sKP9FZq6WN2NBYhIi7shG-H3Cdyfc; username=ra
//     dar\r\n' +
//     'User-Agent: axios/1.7.2\r\n' +
//     'Content-Length: 78\r\n' +
//     'Accept-Encoding: gzip, compress, deflate, br\r\n' +
//     'Host: localhost:3000\r\n' +
//     'Connection: keep-alive\r\n' +
//     '\r\n',
//         _keepAliveTimeout: 0,
//         _onPendingData: [Function: nop],
//     agent: Agent {
//         _events: [Object: null prototype],
//         _eventsCount: 2,
//             _maxListeners: undefined,
//             defaultPort: 80,
//             protocol: 'http:',
//             options: [Object: null prototype],
//         requests: [Object: null prototype] {},
//         sockets: [Object: null prototype],
//         freeSockets: [Object: null prototype],
//         keepAliveMsecs: 1000,
//             keepAlive: true,
//             maxSockets: Infinity,
//             maxFreeSockets: 256,
//             scheduling: 'lifo',
//             maxTotalSockets: Infinity,
//             totalSocketCount: 4,
//             [Symbol(shapeMode)]: false,
//             [Symbol(kCapture)]: false
//     },
//     socketPath: undefined,
//         method: 'POST',
//         maxHeaderSize: undefined,
//         insecureHTTPParser: undefined,
//         joinDuplicateHeaders: undefined,
//         path: '/api/handler',
//         _ended: true,
//         res: IncomingMessage {
//         _events: [Object],
//             _readableState: [ReadableState],
//             _maxListeners: undefined,
//             socket: null,
//             httpVersionMajor: 1,
//             httpVersionMinor: 1,
//             httpVersion: '1.1',
//             complete: true,
//             rawHeaders: [Array],
//             rawTrailers: [],
//             joinDuplicateHeaders: undefined,
//             aborted: false,
//             upgrade: false,
//             url: '',
//             method: null,
//             statusCode: 200,
//             statusMessage: 'OK',
//             client: [Socket],
//             _consuming: false,
//             _dumped: false,
//             req: [Circular *1],
//             _eventsCount: 4,
//             responseUrl: 'http://localhost:3000/api/handler',
//             redirects: [],
//             [Symbol(shapeMode)]: true,
//             [Symbol(kCapture)]: false,
//             [Symbol(kHeaders)]: [Object],
//             [Symbol(kHeadersCount)]: 20,
//             [Symbol(kTrailers)]: null,
//             [Symbol(kTrailersCount)]: 0
//     },
//     aborted: false,
//         timeoutCb: null,
//         upgradeOrConnect: false,
//         parser: null,
//         maxHeadersCount: null,
//         reusedSocket: true,
//         host: 'localhost',
//         protocol: 'http:',
//         _redirectable: Writable {
//         _events: [Object],
//             _writableState: [WritableState],
//             _maxListeners: undefined,
//             _options: [Object],
//             _ended: true,
//             _ending: true,
//             _redirectCount: 0,
//             _redirects: [],
//             _requestBodyLength: 78,
//             _requestBodyBuffers: [],
//             _eventsCount: 3,
//             _onNativeResponse: [Function (anonymous)],
//             _currentRequest: [Circular *1],
//             _currentUrl: 'http://localhost:3000/api/handler',
//             [Symbol(shapeMode)]: true,
//             [Symbol(kCapture)]: false
//     },
//     [Symbol(shapeMode)]: false,
//         [Symbol(kCapture)]: false,
//         [Symbol(kBytesWritten)]: 0,
//         [Symbol(kNeedDrain)]: false,
//         [Symbol(corked)]: 0,
//         [Symbol(kOutHeaders)]: [Object: null prototype] {
//         accept: [Array],
//             'content-type': [Array],
//             cookie: [Array],
//             'user-agent': [Array],
//             'content-length': [Array],
//             'accept-encoding': [Array],
//             host: [Array]
//     },
//     [Symbol(errored)]: null,
//         [Symbol(kHighWaterMark)]: 16384,
//         [Symbol(kRejectNonStandardBodyWrites)]: false,
//         [Symbol(kUniqueHeaders)]: null
// },
//     data: { success: true, error: '', body: 'New token pair sent' }
// }
// {
//     status: 200,
//         statusText: 'OK',
//     headers: Object [AxiosHeaders] {
//     'set-cookie': [
//         'access_jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoicmFkYXIiLCJpc3MiOiJsb2NhbGhvc3QiLCJpYXQiOjE3MTY4OTcxNTYsImV4cCI6MTcxNjg5NzQ1Nn0.dSLATm8rg1xt7Km-_hPQg1alXOkcEqtk2neVK-xGq2g; expires=Tue, 28 May 2024 12:22:36 GM
//         T; Max-Age=1800; path=/; domain=localhost; SameSite=none',
//     'refresh_jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoicmFkYXIiLCJpc3MiOiJsb2NhbGhvc3QiLCJpYXQiOjE3MTY4OTcxNTYsImV4cCI6MTcxNjg5ODk1Nn0.s3JSe63Glh8jLlGlSi1uBeZTX97nnhue3j4NOyY3Y4Y; expires=Tue, 28 May 2024 12:22:36 G
//     MT; Max-Age=1800; path=/; domain=localhost; SameSite=none',
//     'username=radar; expires=Tue, 28 May 2024 12:22:36 GMT; Max-Age=1800; path=/; domain=localhost; SameSite=none'
// ],
//     'content-type': 'application/json; charset=utf-8',
//         etag: '"cma8yus7mh1k"',
//         'content-length': '56',
//         vary: 'Accept-Encoding',
//         date: 'Tue, 28 May 2024 11:52:36 GMT',
//         connection: 'keep-alive',
//         'keep-alive': 'timeout=5'
// },
//     config: {
//         transitional: {
//             silentJSONParsing: true,
//                 forcedJSONParsing: true,
//                 clarifyTimeoutError: false
//         },
//         adapter: [ 'xhr', 'http', 'fetch' ],
//             transformRequest: [ [Function: transformRequest] ],
//         transformResponse: [ [Function: transformResponse] ],
//         timeout: 0,
//             xsrfCookieName: 'XSRF-TOKEN',
//             xsrfHeaderName: 'X-XSRF-TOKEN',
//             maxContentLength: -1,
//             maxBodyLength: -1,
//             env: { FormData: [Function], Blob: [class Blob] },
//         validateStatus: [Function: validateStatus],
//         headers: Object [AxiosHeaders] {
//             Accept: 'application/json, text/plain, */*',
//                 'Content-Type': 'application/json',
//                 Cookie: 'access_jwt=jhg; refresh_jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoicmFkYXIiLCJpc3MiOiJsb2NhbGhvc3QiLCJpYXQiOjE3MTY4OTYwMTcsImV4cCI6MTcxNjg5NzgxN30.TiU3niiShfw-P_sKP9FZq6WN2NBYhIi7shG-H3Cdyfc; username=ra
//             dar',
//             'User-Agent': 'axios/1.7.2',
//                 'Content-Length': '78',
//                 'Accept-Encoding': 'gzip, compress, deflate, br'
//         },
//         method: 'post',
//             url: 'http://localhost:3000/api/handler',
//             data: '{"data":null,"url":"http://localhost/test-api/api/index.php/refreshTokenPair"}',
//             withCredentials: true
//     },
//     request: <ref *1> ClientRequest {
//     _events: [Object: null prototype] {
//         abort: [Function (anonymous)],
//             aborted: [Function (anonymous)],
//             connect: [Function (anonymous)],
//             error: [Function (anonymous)],
//             socket: [Function (anonymous)],
//             timeout: [Function (anonymous)],
//             finish: [Function: requestOnFinish]
//     },
//     _eventsCount: 7,
//         _maxListeners: undefined,
//         outputData: [],
//         outputSize: 0,
//         writable: true,
//         destroyed: true,
//         _last: false,
//         chunkedEncoding: false,
//         shouldKeepAlive: true,
//         maxRequestsOnConnectionReached: false,
//         _defaultKeepAlive: true,
//         useChunkedEncodingByDefault: true,
//         sendDate: false,
//         _removedConnection: false,
//         _removedContLen: false,
//         _removedTE: false,
//         strictContentLength: false,
//         _contentLength: '78',
//         _hasBody: true,
//         _trailer: '',
//         finished: true,
//         _headerSent: true,
//         _closed: true,
//         socket: Socket {
//         connecting: false,
//             _hadError: false,
//             _parent: null,
//             _host: 'localhost',
//             _closeAfterHandlingError: false,
//             _events: [Object],
//             _readableState: [ReadableState],
//             _writableState: [WritableState],
//             allowHalfOpen: false,
//             _maxListeners: undefined,
//             _eventsCount: 6,
//             _sockname: null,
//             _pendingData: null,
//             _pendingEncoding: '',
//             server: null,
//             _server: null,
//             timeout: 5000,
//             parser: null,
//             _httpMessage: null,
//             autoSelectFamilyAttemptedAddresses: [Array],
//             [Symbol(async_id_symbol)]: -1,
//             [Symbol(kHandle)]: [TCP],
//             [Symbol(lastWriteQueueSize)]: 0,
//             [Symbol(timeout)]: Timeout {
//             _idleTimeout: 5000,
//                 _idlePrev: [TimersList],
//                 _idleNext: [Timeout],
//                 _idleStart: 6487358,
//                 _onTimeout: [Function: bound ],
//             _timerArgs: undefined,
//                 _repeat: null,
//                 _destroyed: false,
//                 [Symbol(refed)]: false,
//                 [Symbol(kHasPrimitive)]: false,
//                 [Symbol(asyncId)]: 510691,
//                 [Symbol(triggerId)]: 510689
//         },
//         [Symbol(kBuffer)]: null,
//             [Symbol(kBufferCb)]: null,
//             [Symbol(kBufferGen)]: null,
//             [Symbol(shapeMode)]: true,
//             [Symbol(kCapture)]: false,
//             [Symbol(kSetNoDelay)]: true,
//             [Symbol(kSetKeepAlive)]: true,
//             [Symbol(kSetKeepAliveInitialDelay)]: 1,
//             [Symbol(kBytesRead)]: 0,
//             [Symbol(kBytesWritten)]: 0
//     },
//     _header: 'POST /api/handler HTTP/1.1\r\n' +
//     'Accept: application/json, text/plain, */*\r\n' +
//     'Content-Type: application/json\r\n' +
//     'Cookie: access_jwt=jhg; refresh_jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoicmFkYXIiLCJpc3MiOiJsb2NhbGhvc3QiLCJpYXQiOjE3MTY4OTYwMTcsImV4cCI6MTcxNjg5NzgxN30.TiU3niiShfw-P_sKP9FZq6WN2NBYhIi7shG-H3Cdyfc; username=ra
//     dar\r\n' +
//     'User-Agent: axios/1.7.2\r\n' +
//     'Content-Length: 78\r\n' +
//     'Accept-Encoding: gzip, compress, deflate, br\r\n' +
//     'Host: localhost:3000\r\n' +
//     'Connection: keep-alive\r\n' +
//     '\r\n',
//         _keepAliveTimeout: 0,
//         _onPendingData: [Function: nop],
//     agent: Agent {
//         _events: [Object: null prototype],
//         _eventsCount: 2,
//             _maxListeners: undefined,
//             defaultPort: 80,
//             protocol: 'http:',
//             options: [Object: null prototype],
//         requests: [Object: null prototype] {},
//         sockets: [Object: null prototype],
//         freeSockets: [Object: null prototype],
//         keepAliveMsecs: 1000,
//             keepAlive: true,
//             maxSockets: Infinity,
//             maxFreeSockets: 256,
//             scheduling: 'lifo',
//             maxTotalSockets: Infinity,
//             totalSocketCount: 4,
//             [Symbol(shapeMode)]: false,
//             [Symbol(kCapture)]: false
//     },
//     socketPath: undefined,
//         method: 'POST',
//         maxHeaderSize: undefined,
//         insecureHTTPParser: undefined,
//         joinDuplicateHeaders: undefined,
//         path: '/api/handler',
//         _ended: true,
//         res: IncomingMessage {
//         _events: [Object],
//             _readableState: [ReadableState],
//             _maxListeners: undefined,
//             socket: null,
//             httpVersionMajor: 1,
//             httpVersionMinor: 1,
//             httpVersion: '1.1',
//             complete: true,
//             rawHeaders: [Array],
//             rawTrailers: [],
//             joinDuplicateHeaders: undefined,
//             aborted: false,
//             upgrade: false,
//             url: '',
//             method: null,
//             statusCode: 200,
//             statusMessage: 'OK',
//             client: [Socket],
//             _consuming: false,
//             _dumped: false,
//             req: [Circular *1],
//             _eventsCount: 4,
//             responseUrl: 'http://localhost:3000/api/handler',
//             redirects: [],
//             [Symbol(shapeMode)]: true,
//             [Symbol(kCapture)]: false,
//             [Symbol(kHeaders)]: [Object],
//             [Symbol(kHeadersCount)]: 20,
//             [Symbol(kTrailers)]: null,
//             [Symbol(kTrailersCount)]: 0
//     },
//     aborted: false,
//         timeoutCb: null,
//         upgradeOrConnect: false,
//         parser: null,
//         maxHeadersCount: null,
//         reusedSocket: true,
//         host: 'localhost',
//         protocol: 'http:',
//         _redirectable: Writable {
//         _events: [Object],
//             _writableState: [WritableState],
//             _maxListeners: undefined,
//             _options: [Object],
//             _ended: true,
//             _ending: true,
//             _redirectCount: 0,
//             _redirects: [],
//             _requestBodyLength: 78,
//             _requestBodyBuffers: [],
//             _eventsCount: 3,
//             _onNativeResponse: [Function (anonymous)],
//             _currentRequest: [Circular *1],
//             _currentUrl: 'http://localhost:3000/api/handler',
//             [Symbol(shapeMode)]: true,
//             [Symbol(kCapture)]: false
//     },
//     [Symbol(shapeMode)]: false,
//         [Symbol(kCapture)]: false,
//         [Symbol(kBytesWritten)]: 0,
//         [Symbol(kNeedDrain)]: false,
//         [Symbol(corked)]: 0,
//         [Symbol(kOutHeaders)]: [Object: null prototype] {
//         accept: [Array],
//             'content-type': [Array],
//             cookie: [Array],
//             'user-agent': [Array],
//             'content-length': [Array],
//             'accept-encoding': [Array],
//             host: [Array]
//     },
//     [Symbol(errored)]: null,
//         [Symbol(kHighWaterMark)]: 16384,
//         [Symbol(kRejectNonStandardBodyWrites)]: false,
//         [Symbol(kUniqueHeaders)]: null
// },
//     data: { success: true, error: '', body: 'New token pair sent' }
// }
